[package]
name = "escalation-macros"
version = "0.1.0"
edition = "2024"
description = "macro helper for escalation crate."
license = "MIT OR Apache-2.0"
repository = "https://github.com/anotherhollow1125/escalation"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = { version = "2.0.119", features = ["full"] }
