[package]
name = "escalation"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["escalation-macros"]

[features]
default = ["serde"]
serde = ["dep:serde"]

[dependencies]
escalation-macros = { path = "escalation-macros" }
serde = { version = "1.0.229", features = ["derive"], optional = true }
thiserror = "2.0.21"

[dev-dependencies]
clap = { version = "4.6.7", features = ["derive"] }
anyhow = "1.0.104"
hooq = "0.3.1"
serde_json = "1.0.151"
