[default]
method = """.map_err(|mut e| {
    use ::escalation::{IntoNewReport, LocationInfo, Recognize};

    let path = $path;
    let fn_name = $fn_name;
    let line = $line as u32;
    let col = $col as u32;
    let expr = ::hooq::source_excerpt_helpers::one_line_stringify!($source);
    let tag = $tag;

    let info = LocationInfo {
        path,
        fn_name,
        line,
        col,
        tag,
        expr,
    };

    e.into_new_report(info, $error)
})"""
bindings = { tag = "\"no_tag\"", error = "None" }
